# Generated by Django 3.0.1 on 2020-02-14 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='fid',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
    ]
