# Generated by Django 3.0.3 on 2020-03-12 15:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userprofile',
            options={'ordering': ['-score', '-level', 'submission_count']},
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='user',
        ),
        migrations.AddField(
            model_name='hintmodel',
            name='fid',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='submission',
            name='fid',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='name',
            field=models.CharField(blank=True, default=None, max_length=70, null=True),
        ),
        migrations.AlterField(
            model_name='hintmodel',
            name='hintviewed',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='hintmodel',
            name='ques',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Question'),
        ),
        migrations.AlterField(
            model_name='hintmodel',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.UserProfile'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='ques',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='core.Question'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.UserProfile'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='fid',
            field=models.SlugField(default=None, max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='pic',
            field=models.CharField(blank=True, default=None, max_length=500, null=True),
        ),
    ]
