# Generated by Django 3.0.1 on 2020-02-14 16:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20200214_1055'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='pic',
            field=models.CharField(blank=True, default=None, max_length=500, null=True),
        ),
    ]
