# Generated by Django 3.0.3 on 2020-03-12 18:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20200312_2240'),
    ]

    operations = [
        migrations.RenameField(
            model_name='submission',
            old_name='status',
            new_name='response',
        ),
    ]
