# Generated by Django 3.0.1 on 2020-02-20 03:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20200214_2224'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='user_profile',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='core.UserProfile'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='submission',
            name='ques',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='core.Question'),
        ),
    ]
