# Generated by Django 3.0.3 on 2020-03-27 13:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20200312_2330'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='pic',
            field=models.ImageField(blank=True, null=True, upload_to='manan/xunbao2020'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='ques',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Question'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='fid',
            field=models.CharField(default=None, max_length=100, unique=True),
        ),
        migrations.AlterUniqueTogether(
            name='hintmodel',
            unique_together=set(),
        ),
    ]
