# Generated by Django 3.0.1 on 2020-02-20 03:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_auto_20200220_0848'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='submission',
            name='user_profile',
        ),
    ]
