# Generated by Django 3.0.3 on 2020-03-27 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20200327_1910'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='pic',
        ),
    ]
