# Generated by Django 3.0.3 on 2020-03-27 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_remove_question_pic'),
    ]

    operations = [
        migrations.AddField(
            model_name='hintmodel',
            name='hint',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
    ]
