# Generated by Django 3.0.3 on 2020-03-31 17:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_hintmodel_hint'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='answer',
            field=models.CharField(max_length=10000),
        ),
        migrations.AlterField(
            model_name='hintmodel',
            name='hint',
            field=models.CharField(blank=True, default=None, max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='hint',
            field=models.CharField(max_length=10000),
        ),
        migrations.AlterField(
            model_name='submission',
            name='answer',
            field=models.CharField(max_length=10000),
        ),
        migrations.AlterField(
            model_name='submission',
            name='ques',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.Question'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='score',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
