# Generated by Django 3.0.3 on 2020-03-10 16:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_auto_20200310_0032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hintmodel',
            name='ques',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.Question'),
        ),
        migrations.AlterField(
            model_name='hintmodel',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.UserProfile'),
        ),
    ]
