# Generated by Django 3.0.3 on 2020-03-12 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_auto_20200310_2225'),
    ]

    operations = [
        migrations.AddField(
            model_name='hintmodel',
            name='fid',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='submission',
            name='fid',
            field=models.CharField(blank=True, default=None, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='fid',
            field=models.SlugField(blank=True, default=None, max_length=100, null=True),
        ),
    ]
